version: "3"
services:
  node:
    container_name: nodedev
    image: "node:12"
    user: "node"
    working_dir: /var/www
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/var/www
    ports:
    - ${port:-3000}:3000
    # expose:
    #   - "3000"
    command: "npm start"
